import { IItemProduct } from '@/types/elements';
import { TypeItemCart } from '@/types/main-page';
import { v4 } from 'uuid';

export const FAKE_ITEMS_BASKET_NOTIFICATON: TypeItemCart[] = [
  {
    id: v4(),
    href: '/',
    image: '/img/item-test-1.jpg',
    description: 'Олива моторна HDX 20W-50 1л',
  },
  {
    id: v4(),
    href: '/',
    image: '/img/item-test-2.jpg',
    description: 'Губка для миття автомобіля AUTO...',
  },
  {
    id: v4(),
    href: '/',
    image: '/img/item-test-3.webp',
    description: 'Фільтр паливний',
  },
];

export const FAKE_LIST_PRODUCTS: IItemProduct[] = [
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: null,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: false,
    quantityAvailable: 122,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'AUTO car wash sponge',
      ru: 'Губка для мойки автомобилей AUTO',
      ua: 'Губка для миття автомобіля AUTO',
    },
    brand: 'AUTO',
    sku: 'KL 02336',
    price: 100.58,
    salePrice: 100,
    photos: ['/img/item-test-2.jpg'],
    description: {
      en: 'AUTO car wash sponge description',
      ru: 'Губка для мойки автомобилей AUTO description',
      ua: 'Губка для миття автомобіля AUTO description',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 122,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: null,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: false,
    quantityAvailable: 122,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'AUTO car wash sponge',
      ru: 'Губка для мойки автомобилей AUTO',
      ua: 'Губка для миття автомобіля AUTO',
    },
    brand: 'AUTO',
    sku: 'KL 02336',
    price: 100.58,
    salePrice: 100,
    photos: ['/img/item-test-2.jpg'],
    description: {
      en: 'AUTO car wash sponge description',
      ru: 'Губка для мойки автомобилей AUTO description',
      ua: 'Губка для миття автомобіля AUTO description',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 122,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: null,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: false,
    quantityAvailable: 122,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'AUTO car wash sponge',
      ru: 'Губка для мойки автомобилей AUTO',
      ua: 'Губка для миття автомобіля AUTO',
    },
    brand: 'AUTO',
    sku: 'KL 02336',
    price: 100.58,
    salePrice: 100,
    photos: ['/img/item-test-2.jpg'],
    description: {
      en: 'AUTO car wash sponge description',
      ru: 'Губка для мойки автомобилей AUTO description',
      ua: 'Губка для миття автомобіля AUTO description',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 122,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
  {
    id: v4(),
    name: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    brand: 'HDX',
    sku: 'KL 02335',
    price: 1393.58,
    salePrice: 1300,
    photos: ['/img/item-test-1.jpg'],
    description: {
      en: 'HDX 20W-50 Engine Oil 1L',
      ru: 'Масло моторное HDX 20W-50 1л',
      ua: 'Олива моторна HDX 20W-50 1л',
    },
    country: 'Ukraine',
    manufacturerWebsite: 'https://www.kroon-oil.com/',
    availability: true,
    quantityAvailable: 0,
    rating: 3.4,
  },
];
